totem {
    version:        2
    transport:      udpu
    token:          3000
    consensus:      4800
    join:           60
    max_messages:   20
    secauth:        off
}

nodelist {
    node {
        ring0_addr: 172.20.0.2
        name:       webz-001
        nodeid:     1
    }
    node {
        ring0_addr: 172.20.0.3
        name:       webz-002
        nodeid:     2
    }
    node {
        ring0_addr: 172.20.0.4
        name:       webz-003
        nodeid:     3
    }
}

quorum {
    provider: corosync_votequorum
    two_node: 0
}

logging {
    to_logfile:     yes
    logfile:        /var/log/corosync/corosync.log
    to_syslog:      yes
    debug:          off
}